# Generated by Django 5.2.6 on 2025-09-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('astronaut', 'Astronaut'), ('admin', 'Admin')], default='astronaut', max_length=50),
        ),
        migrations.AlterField(
            model_name='radiationlog',
            name='alert_level',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='radiationlog',
            name='cumulative_dose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='radiationlog',
            name='dose_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='radiationlog',
            name='event_type',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='radiationlog',
            name='exposure_duration',
            field=models.FloatField(),
        ),
    ]
